### PR TITLE
Update inference_rules.adoc

### PR DESCRIPTION
**Pull request by DilipSequeira**
Allow sorting of embedding tables.

### CODE REVIEW

**Comment by christ1ne** [comment]
is this really just sorting the embedding tables? How about the entries in the embedding tables?

**Comment by DilipSequeira** [comment]
Can you expand on the question? If I think about e.g. sorting a list, and sorting the entries in a list, I see them as different phrases for the same thing.

For context, the goal here is to improve locality of reference at e.g. page level by clustering frequently accessed elements.

**Comment by christ1ne** [comment]
Agree. somehow my first impression to your wording is for sorting at table level rather than sorting at the table entry level. I hope it is just me.

**Comment by DilipSequeira** [comment]
Fair point. I've updated the wording to remove that ambiguity.

**Comment by christ1ne** [comment]
@tjablin @mnaumovfb can you comment if using the prior knowledge of embedding table access frequency is a recommended practice from real world use cases? Thanks!

**Comment by tjablin** [comment]
Embedding table frequencies tend to be stable, and sorting an embedding table doesn't affect model quality. Sorting an embedding table by frequency is exactly the type of technique Google would use on platforms where it improves performance.

**Comment by mnaumovfb** [comment]
I think that allowing sorting based on training set is reasonable.

**Pull request merged**
