### PR TITLE
Update QSL sizes and quality targets of v0.7 new benchmarks

### PR DESCRIPTION
**Pull request by nvpohanh**
Update QSL sizes and quality targets of v0.7 new benchmarks

@TheKanter I ended up filing a PR for all the new benchmarks.

@galv @mnaumovfb FYI. Please correct me if I fill in any of these incorrectly.

### CODE REVIEW

**Comment by christ1ne** [comment]
@nvpohanh since you are touching the table, will you update the 
Machine translation to Question answering for BERT?

**Comment by nvpohanh** [comment]
@christ1ne good point. will do

**Comment by nvpohanh** [comment]
@christ1ne updated!

**Comment by christ1ne** [comment]
LGTM @tjablin Just FYI

**Comment by galv** [comment]
@nvpohanh yes, the Speech-to-text one looks good.

**Pull request merged**
