### PR TITLE
Update inference_rules.adoc

### PR DESCRIPTION
**Pull request by DilipSequeira**
Add new QSL size for GNMT

### CODE REVIEW

**Comment by christ1ne** [comment]
Actually it is 3,903,900  for performance mode and 3003 for accuracy mode. Can you make this explicit? Thanks!

**Comment by DilipSequeira** [comment]
I would if there were a column in the table for the accuracy count - the table is explicitly noted to be the perf QSL size, and I guess the accuracy set is always taken to be the validation set size from the data set with which the model was trained (which is 3003 in the GNMT case.)

**Comment by christ1ne** [comment]
ok.

**Comment by christ1ne** [comment]
WG approved

**Pull request merged**
